In [3]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("C:\\Users\\Tejas\\Downloads\\Advertising.csv")

In [8]:
df.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

df.isnull().sum()

In [10]:
df.isnull().sum()

Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [12]:
df.describe

<bound method NDFrame.describe of      Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]>

In [14]:
df.info

<bound method DataFrame.info of      Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]>

In [26]:
from sklearn.preprocessing import StandardScaler

In [28]:
scaler=StandardScaler()

In [32]:
col=["TV","Radio","Newspaper","Sales"]
df[col]=scaler.fit_transform(df[col])
df

     Unnamed: 0        TV     Radio  Newspaper     Sales
0             1  0.969852  0.981522   1.778945  1.552053
1             2 -1.197376  1.082808   0.669579 -0.696046
2             3 -1.516155  1.528463   1.783549 -0.907406
3             4  0.052050  1.217855   1.286405  0.860330
4             5  0.394182 -0.841614   1.281802 -0.215683
..          ...       ...       ...        ...       ...
195         196 -1.270941 -1.321031  -0.771217 -1.234053
196         197 -0.617035 -1.240003  -1.033598 -0.830548
197         198  0.349810 -0.942899  -1.111852 -0.234898
198         199  1.594565  1.265121   1.640850  2.205347
199         200  0.993206 -0.990165  -1.005979 -0.119610

[200 rows x 5 columns]

In [46]:
X=df.drop(['Unnamed: 0','Sales'],axis=1)
y=df['Sales']

In [48]:
from sklearn.model_selection import train_test_split

In [52]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=100)

In [54]:
X.shape

(200, 3)

In [56]:
y.shape

(200,)

In [60]:
from sklearn.linear_model import LinearRegression
lr_model=LinearRegression()
lr_model.fit(X_train,y_train)

LinearRegression()

In [62]:
lr_model.score(X_train,y_train)

0.89152823018429

In [70]:
y_pred=lr_model.predict(X_test)
y_pred

array([-0.6750086 ,  1.15954568,  0.53880505,  0.97447567,  1.3299022 ,
       -0.14776181, -0.41252714, -0.29479608,  1.24734996,  1.32403199,
       -0.59962361,  1.04153827, -1.44463922,  0.24889404, -0.95707983,
       -1.14960101,  0.43104133, -0.36879964,  0.59533627, -0.52670587,
        0.58563208, -0.80277869,  1.28319869,  0.60569858,  0.22528703,
        1.52636583,  0.98690657, -0.75519423,  1.03367311,  0.16511111,
        0.04917779, -1.21642557, -0.77255228,  0.1540138 , -1.29327629,
       -0.07454479, -1.23524321, -0.41915306, -0.07804683,  0.22396617])

In [74]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [76]:
mean_squared_error(y_test,y_pred)

0.06399280734466724

In [82]:
mean_absolute_error(y_test,y_pred)

0.19736543419187957

In [84]:
r2_score(y_test,y_pred)

0.9184369032278497